version: "3.8"


services:

# For Message Queue Kafka
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: always
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes


  kafka:
    image: 'bitnami/kafka:latest'
    restart: always
    ports:
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
# End of Message Queue Kafka
 
  login:
    build:
      context: ./login
      dockerfile: Dockerfile
    image: jsebastian2020/login:proj
    restart: always
    

  driver:
    build:
      context: ./driver
      dockerfile: Dockerfile
    image: jsebastian2020/driver:proj
    restart: always

  parcel:
    build:
      context: ./parcel
      dockerfile: Dockerfile
    image: jsebastian2020/parcel:proj
    restart: always

  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile
    image: jsebastian2020/customer:proj
    restart: always
  
  sms:
    build:
      context: ./sms-node
      dockerfile: Dockerfile
    image: jsebastian2020/sms:proj
    restart: always
    depends_on:
      - kafka
      - zookeeper

  loadDashboard:
    build:
      context: ./load_dashboard
      dockerfile: Dockerfile
    image: jsebastian2020/load_dashboard:proj
    restart: always
    environment:
      loginURL : 'http://login:5001/authenticate'
      driverURL : 'http://driver:5002/driver'
      parcelURL : 'http://parcel:5003/parcel'
    ports:
      - "5000:5000"
    depends_on:
      - login
      - driver
      - parcel

  getDeliveryAddresses:
    build:
      context: ./get_delivery_addresses
      dockerfile: Dockerfile
    image: jsebastian2020/get_delivery_addresses:proj
    restart: always
    environment:
      customerURL : 'http://customer:5004/customer'
    ports:
      - "5010:5010"
    depends_on:
      - customer
    
  updateParcelStatus:
    build:
      context: ./update_parcel_status
      dockerfile: Dockerfile
    image: jsebastian2020/update_parcel_status:proj
    restart: always
    environment:
      customerURL : 'http://customer:5004/customer'
      parcelURL : 'http://parcel:5003/parcel'
    ports:
      - "5020:5020"
    depends_on:
      - parcel
      - customer
      - sms





